// This file has been generated by Py++.

#include "boost/python.hpp"
#include "bindings/control.h"
#include "_control_free_functions.pypp.hpp"

namespace bp = boost::python;

void register_free_functions(){

    { //::ompl::control::dummyODESolverSize
    
        typedef int ( *dummyODESolverSize_function_type )(  );
        
        bp::def( 
            "dummyODESolverSize"
            , dummyODESolverSize_function_type( &::ompl::control::dummyODESolverSize ) );
    
    }

}
