// This file has been generated by Py++.

#ifndef _control_enumerations_hpp__pyplusplus_wrapper
#define _control_enumerations_hpp__pyplusplus_wrapper

void register_enumerations();

#endif//_control_enumerations_hpp__pyplusplus_wrapper
