// This file has been generated by Py++.

#ifndef CompoundControl_hpp__pyplusplus_wrapper
#define CompoundControl_hpp__pyplusplus_wrapper

void register_CompoundControl_class();

#endif//CompoundControl_hpp__pyplusplus_wrapper
