// This file has been generated by Py++.

#ifndef CompoundControlSampler_hpp__pyplusplus_wrapper
#define CompoundControlSampler_hpp__pyplusplus_wrapper

void register_CompoundControlSampler_class();

#endif//CompoundControlSampler_hpp__pyplusplus_wrapper
