// This file has been generated by Py++.

#ifndef DiscreteControlSpace_hpp__pyplusplus_wrapper
#define DiscreteControlSpace_hpp__pyplusplus_wrapper

void register_DiscreteControlSpace_class();

#endif//DiscreteControlSpace_hpp__pyplusplus_wrapper
