// This file has been generated by Py++.

#include "boost/python.hpp"
#include "bindings/control.h"
#include "RealVectorControlSpace.pypp.hpp"

namespace bp = boost::python;

struct RealVectorControlSpace_wrapper : ompl::control::RealVectorControlSpace, bp::wrapper< ompl::control::RealVectorControlSpace > {

    RealVectorControlSpace_wrapper(::ompl::base::StateSpacePtr const & stateSpace, unsigned int dim )
    : ompl::control::RealVectorControlSpace( stateSpace, dim )
      , bp::wrapper< ompl::control::RealVectorControlSpace >(){
        // constructor
    
    }

    virtual ::ompl::control::Control * allocControl(  ) const  {
        if( bp::override func_allocControl = this->get_override( "allocControl" ) )
            return func_allocControl(  );
        else{
            return this->ompl::control::RealVectorControlSpace::allocControl(  );
        }
    }
    
    ::ompl::control::Control * default_allocControl(  ) const  {
        return ompl::control::RealVectorControlSpace::allocControl( );
    }

    virtual ::ompl::control::ControlSamplerPtr allocDefaultControlSampler(  ) const  {
        if( bp::override func_allocDefaultControlSampler = this->get_override( "allocDefaultControlSampler" ) )
            return func_allocDefaultControlSampler(  );
        else{
            return this->ompl::control::RealVectorControlSpace::allocDefaultControlSampler(  );
        }
    }
    
    ::ompl::control::ControlSamplerPtr default_allocDefaultControlSampler(  ) const  {
        return ompl::control::RealVectorControlSpace::allocDefaultControlSampler( );
    }

    virtual void copyControl( ::ompl::control::Control * destination, ::ompl::control::Control const * source ) const  {
        if( bp::override func_copyControl = this->get_override( "copyControl" ) )
            func_copyControl( boost::python::ptr(destination), boost::python::ptr(source) );
        else{
            this->ompl::control::RealVectorControlSpace::copyControl( boost::python::ptr(destination), boost::python::ptr(source) );
        }
    }
    
    void default_copyControl( ::ompl::control::Control * destination, ::ompl::control::Control const * source ) const  {
        ompl::control::RealVectorControlSpace::copyControl( boost::python::ptr(destination), boost::python::ptr(source) );
    }

    virtual void deserialize( ::ompl::control::Control * ctrl, void const * serialization ) const  {
        if( bp::override func_deserialize = this->get_override( "deserialize" ) )
            func_deserialize( boost::python::ptr(ctrl), serialization );
        else{
            this->ompl::control::RealVectorControlSpace::deserialize( boost::python::ptr(ctrl), serialization );
        }
    }
    
    void default_deserialize( ::ompl::control::Control * ctrl, void const * serialization ) const  {
        ompl::control::RealVectorControlSpace::deserialize( boost::python::ptr(ctrl), serialization );
    }

    virtual bool equalControls( ::ompl::control::Control const * control1, ::ompl::control::Control const * control2 ) const  {
        if( bp::override func_equalControls = this->get_override( "equalControls" ) )
            return func_equalControls( boost::python::ptr(control1), boost::python::ptr(control2) );
        else{
            return this->ompl::control::RealVectorControlSpace::equalControls( boost::python::ptr(control1), boost::python::ptr(control2) );
        }
    }
    
    bool default_equalControls( ::ompl::control::Control const * control1, ::ompl::control::Control const * control2 ) const  {
        return ompl::control::RealVectorControlSpace::equalControls( boost::python::ptr(control1), boost::python::ptr(control2) );
    }

    virtual void freeControl( ::ompl::control::Control * control ) const  {
        if( bp::override func_freeControl = this->get_override( "freeControl" ) )
            func_freeControl( boost::python::ptr(control) );
        else{
            this->ompl::control::RealVectorControlSpace::freeControl( boost::python::ptr(control) );
        }
    }
    
    void default_freeControl( ::ompl::control::Control * control ) const  {
        ompl::control::RealVectorControlSpace::freeControl( boost::python::ptr(control) );
    }

    virtual unsigned int getDimension(  ) const  {
        if( bp::override func_getDimension = this->get_override( "getDimension" ) )
            return func_getDimension(  );
        else{
            return this->ompl::control::RealVectorControlSpace::getDimension(  );
        }
    }
    
    unsigned int default_getDimension(  ) const  {
        return ompl::control::RealVectorControlSpace::getDimension( );
    }

    virtual unsigned int getSerializationLength(  ) const  {
        if( bp::override func_getSerializationLength = this->get_override( "getSerializationLength" ) )
            return func_getSerializationLength(  );
        else{
            return this->ompl::control::RealVectorControlSpace::getSerializationLength(  );
        }
    }
    
    unsigned int default_getSerializationLength(  ) const  {
        return ompl::control::RealVectorControlSpace::getSerializationLength( );
    }

    virtual void nullControl( ::ompl::control::Control * control ) const  {
        if( bp::override func_nullControl = this->get_override( "nullControl" ) )
            func_nullControl( boost::python::ptr(control) );
        else{
            this->ompl::control::RealVectorControlSpace::nullControl( boost::python::ptr(control) );
        }
    }
    
    void default_nullControl( ::ompl::control::Control * control ) const  {
        ompl::control::RealVectorControlSpace::nullControl( boost::python::ptr(control) );
    }

    virtual void serialize( void * serialization, ::ompl::control::Control const * ctrl ) const  {
        if( bp::override func_serialize = this->get_override( "serialize" ) )
            func_serialize( serialization, boost::python::ptr(ctrl) );
        else{
            this->ompl::control::RealVectorControlSpace::serialize( serialization, boost::python::ptr(ctrl) );
        }
    }
    
    void default_serialize( void * serialization, ::ompl::control::Control const * ctrl ) const  {
        ompl::control::RealVectorControlSpace::serialize( serialization, boost::python::ptr(ctrl) );
    }

    virtual void setup(  ) {
        if( bp::override func_setup = this->get_override( "setup" ) )
            func_setup(  );
        else{
            this->ompl::control::RealVectorControlSpace::setup(  );
        }
    }
    
    void default_setup(  ) {
        ompl::control::RealVectorControlSpace::setup( );
    }

    virtual ::ompl::control::ControlSamplerPtr allocControlSampler(  ) const  {
        if( bp::override func_allocControlSampler = this->get_override( "allocControlSampler" ) )
            return func_allocControlSampler(  );
        else{
            return this->ompl::control::ControlSpace::allocControlSampler(  );
        }
    }
    
    ::ompl::control::ControlSamplerPtr default_allocControlSampler(  ) const  {
        return ompl::control::ControlSpace::allocControlSampler( );
    }

    virtual bool isCompound(  ) const  {
        if( bp::override func_isCompound = this->get_override( "isCompound" ) )
            return func_isCompound(  );
        else{
            return this->ompl::control::ControlSpace::isCompound(  );
        }
    }
    
    bool default_isCompound(  ) const  {
        return ompl::control::ControlSpace::isCompound( );
    }

};

std::string __printSettings(::ompl::control::RealVectorControlSpace* obj)
{
    std::ostringstream s;
    obj->printSettings(s);
    return s.str();
}

std::string __printControl(::ompl::control::RealVectorControlSpace* space, ompl::control::Control* control)
        {
            std::ostringstream s;
            space->printControl(control, s);
            return s.str();
        }

double __getitem(::ompl::control::RealVectorControlSpace::ControlType* obj, unsigned int i)
{
    return (*obj)[i];
}

void __setitem(::ompl::control::RealVectorControlSpace::ControlType* obj, unsigned int i, double val)
{
    (*obj)[i] = val;
}

void register_RealVectorControlSpace_class(){

    { //::ompl::control::RealVectorControlSpace
        typedef bp::class_< RealVectorControlSpace_wrapper, bp::bases< ompl::control::ControlSpace >, boost::noncopyable > RealVectorControlSpace_exposer_t;
        RealVectorControlSpace_exposer_t RealVectorControlSpace_exposer = RealVectorControlSpace_exposer_t( "RealVectorControlSpace", bp::init< ompl::base::StateSpacePtr const &, unsigned int >(( bp::arg("stateSpace"), bp::arg("dim") )) );
        bp::scope RealVectorControlSpace_scope( RealVectorControlSpace_exposer );
        { //::ompl::control::RealVectorControlSpace::ControlType
            typedef bp::class_< ompl::control::RealVectorControlSpace::ControlType, bp::bases< ompl::control::Control >, boost::noncopyable > ControlType_exposer_t;
            ControlType_exposer_t ControlType_exposer = ControlType_exposer_t( "ControlType" );
            bp::scope ControlType_scope( ControlType_exposer );
            ControlType_exposer.def("__getitem__", &__getitem);
            ControlType_exposer.def("__setitem__", &__setitem);
        }
        { //::ompl::control::RealVectorControlSpace::allocControl
        
            typedef ::ompl::control::Control * ( ::ompl::control::RealVectorControlSpace::*allocControl_function_type)(  ) const;
            typedef ::ompl::control::Control * ( RealVectorControlSpace_wrapper::*default_allocControl_function_type)(  ) const;
            
            RealVectorControlSpace_exposer.def( 
                "allocControl"
                , allocControl_function_type(&::ompl::control::RealVectorControlSpace::allocControl)
                , default_allocControl_function_type(&RealVectorControlSpace_wrapper::default_allocControl)
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::ompl::control::RealVectorControlSpace::allocDefaultControlSampler
        
            typedef ::ompl::control::ControlSamplerPtr ( ::ompl::control::RealVectorControlSpace::*allocDefaultControlSampler_function_type)(  ) const;
            typedef ::ompl::control::ControlSamplerPtr ( RealVectorControlSpace_wrapper::*default_allocDefaultControlSampler_function_type)(  ) const;
            
            RealVectorControlSpace_exposer.def( 
                "allocDefaultControlSampler"
                , allocDefaultControlSampler_function_type(&::ompl::control::RealVectorControlSpace::allocDefaultControlSampler)
                , default_allocDefaultControlSampler_function_type(&RealVectorControlSpace_wrapper::default_allocDefaultControlSampler) );
        
        }
        { //::ompl::control::RealVectorControlSpace::copyControl
        
            typedef void ( ::ompl::control::RealVectorControlSpace::*copyControl_function_type)( ::ompl::control::Control *,::ompl::control::Control const * ) const;
            typedef void ( RealVectorControlSpace_wrapper::*default_copyControl_function_type)( ::ompl::control::Control *,::ompl::control::Control const * ) const;
            
            RealVectorControlSpace_exposer.def( 
                "copyControl"
                , copyControl_function_type(&::ompl::control::RealVectorControlSpace::copyControl)
                , default_copyControl_function_type(&RealVectorControlSpace_wrapper::default_copyControl)
                , ( bp::arg("destination"), bp::arg("source") ) );
        
        }
        { //::ompl::control::RealVectorControlSpace::deserialize
        
            typedef void ( ::ompl::control::RealVectorControlSpace::*deserialize_function_type)( ::ompl::control::Control *,void const * ) const;
            typedef void ( RealVectorControlSpace_wrapper::*default_deserialize_function_type)( ::ompl::control::Control *,void const * ) const;
            
            RealVectorControlSpace_exposer.def( 
                "deserialize"
                , deserialize_function_type(&::ompl::control::RealVectorControlSpace::deserialize)
                , default_deserialize_function_type(&RealVectorControlSpace_wrapper::default_deserialize)
                , ( bp::arg("ctrl"), bp::arg("serialization") ) );
        
        }
        { //::ompl::control::RealVectorControlSpace::equalControls
        
            typedef bool ( ::ompl::control::RealVectorControlSpace::*equalControls_function_type)( ::ompl::control::Control const *,::ompl::control::Control const * ) const;
            typedef bool ( RealVectorControlSpace_wrapper::*default_equalControls_function_type)( ::ompl::control::Control const *,::ompl::control::Control const * ) const;
            
            RealVectorControlSpace_exposer.def( 
                "equalControls"
                , equalControls_function_type(&::ompl::control::RealVectorControlSpace::equalControls)
                , default_equalControls_function_type(&RealVectorControlSpace_wrapper::default_equalControls)
                , ( bp::arg("control1"), bp::arg("control2") ) );
        
        }
        { //::ompl::control::RealVectorControlSpace::freeControl
        
            typedef void ( ::ompl::control::RealVectorControlSpace::*freeControl_function_type)( ::ompl::control::Control * ) const;
            typedef void ( RealVectorControlSpace_wrapper::*default_freeControl_function_type)( ::ompl::control::Control * ) const;
            
            RealVectorControlSpace_exposer.def( 
                "freeControl"
                , freeControl_function_type(&::ompl::control::RealVectorControlSpace::freeControl)
                , default_freeControl_function_type(&RealVectorControlSpace_wrapper::default_freeControl)
                , ( bp::arg("control") ) );
        
        }
        { //::ompl::control::RealVectorControlSpace::getBounds
        
            typedef ::ompl::base::RealVectorBounds const & ( ::ompl::control::RealVectorControlSpace::*getBounds_function_type)(  ) const;
            
            RealVectorControlSpace_exposer.def( 
                "getBounds"
                , getBounds_function_type( &::ompl::control::RealVectorControlSpace::getBounds )
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::ompl::control::RealVectorControlSpace::getDimension
        
            typedef unsigned int ( ::ompl::control::RealVectorControlSpace::*getDimension_function_type)(  ) const;
            typedef unsigned int ( RealVectorControlSpace_wrapper::*default_getDimension_function_type)(  ) const;
            
            RealVectorControlSpace_exposer.def( 
                "getDimension"
                , getDimension_function_type(&::ompl::control::RealVectorControlSpace::getDimension)
                , default_getDimension_function_type(&RealVectorControlSpace_wrapper::default_getDimension) );
        
        }
        { //::ompl::control::RealVectorControlSpace::getSerializationLength
        
            typedef unsigned int ( ::ompl::control::RealVectorControlSpace::*getSerializationLength_function_type)(  ) const;
            typedef unsigned int ( RealVectorControlSpace_wrapper::*default_getSerializationLength_function_type)(  ) const;
            
            RealVectorControlSpace_exposer.def( 
                "getSerializationLength"
                , getSerializationLength_function_type(&::ompl::control::RealVectorControlSpace::getSerializationLength)
                , default_getSerializationLength_function_type(&RealVectorControlSpace_wrapper::default_getSerializationLength) );
        
        }
        { //::ompl::control::RealVectorControlSpace::nullControl
        
            typedef void ( ::ompl::control::RealVectorControlSpace::*nullControl_function_type)( ::ompl::control::Control * ) const;
            typedef void ( RealVectorControlSpace_wrapper::*default_nullControl_function_type)( ::ompl::control::Control * ) const;
            
            RealVectorControlSpace_exposer.def( 
                "nullControl"
                , nullControl_function_type(&::ompl::control::RealVectorControlSpace::nullControl)
                , default_nullControl_function_type(&RealVectorControlSpace_wrapper::default_nullControl)
                , ( bp::arg("control") ) );
        
        }
        { //::ompl::control::RealVectorControlSpace::serialize
        
            typedef void ( ::ompl::control::RealVectorControlSpace::*serialize_function_type)( void *,::ompl::control::Control const * ) const;
            typedef void ( RealVectorControlSpace_wrapper::*default_serialize_function_type)( void *,::ompl::control::Control const * ) const;
            
            RealVectorControlSpace_exposer.def( 
                "serialize"
                , serialize_function_type(&::ompl::control::RealVectorControlSpace::serialize)
                , default_serialize_function_type(&RealVectorControlSpace_wrapper::default_serialize)
                , ( bp::arg("serialization"), bp::arg("ctrl") ) );
        
        }
        { //::ompl::control::RealVectorControlSpace::setBounds
        
            typedef void ( ::ompl::control::RealVectorControlSpace::*setBounds_function_type)( ::ompl::base::RealVectorBounds const & ) ;
            
            RealVectorControlSpace_exposer.def( 
                "setBounds"
                , setBounds_function_type( &::ompl::control::RealVectorControlSpace::setBounds )
                , ( bp::arg("bounds") ) );
        
        }
        { //::ompl::control::RealVectorControlSpace::setup
        
            typedef void ( ::ompl::control::RealVectorControlSpace::*setup_function_type)(  ) ;
            typedef void ( RealVectorControlSpace_wrapper::*default_setup_function_type)(  ) ;
            
            RealVectorControlSpace_exposer.def( 
                "setup"
                , setup_function_type(&::ompl::control::RealVectorControlSpace::setup)
                , default_setup_function_type(&RealVectorControlSpace_wrapper::default_setup) );
        
        }
        { //::ompl::control::ControlSpace::allocControlSampler
        
            typedef ::ompl::control::ControlSamplerPtr ( ::ompl::control::ControlSpace::*allocControlSampler_function_type)(  ) const;
            typedef ::ompl::control::ControlSamplerPtr ( RealVectorControlSpace_wrapper::*default_allocControlSampler_function_type)(  ) const;
            
            RealVectorControlSpace_exposer.def( 
                "allocControlSampler"
                , allocControlSampler_function_type(&::ompl::control::ControlSpace::allocControlSampler)
                , default_allocControlSampler_function_type(&RealVectorControlSpace_wrapper::default_allocControlSampler) );
        
        }
        { //::ompl::control::ControlSpace::isCompound
        
            typedef bool ( ::ompl::control::ControlSpace::*isCompound_function_type)(  ) const;
            typedef bool ( RealVectorControlSpace_wrapper::*default_isCompound_function_type)(  ) const;
            
            RealVectorControlSpace_exposer.def( 
                "isCompound"
                , isCompound_function_type(&::ompl::control::ControlSpace::isCompound)
                , default_isCompound_function_type(&RealVectorControlSpace_wrapper::default_isCompound) );
        
        }
        RealVectorControlSpace_exposer.def("settings", &__printSettings);
        RealVectorControlSpace_exposer.def("string", &__printControl);
    }

}
