// This file has been generated by Py++.

#ifndef OutputHandler_hpp__pyplusplus_wrapper
#define OutputHandler_hpp__pyplusplus_wrapper

void register_OutputHandler_class();

#endif//OutputHandler_hpp__pyplusplus_wrapper
