// This file has been generated by Py++.

#ifndef vectorSizeT_hpp__pyplusplus_wrapper
#define vectorSizeT_hpp__pyplusplus_wrapper

void register_vectorSizeT_class();

#endif//vectorSizeT_hpp__pyplusplus_wrapper
