// This file has been generated by Py++.

#ifndef vectorVectorDouble_hpp__pyplusplus_wrapper
#define vectorVectorDouble_hpp__pyplusplus_wrapper

void register_vectorVectorDouble_class();

#endif//vectorVectorDouble_hpp__pyplusplus_wrapper
