// This file has been generated by Py++.

#ifndef vectorPlannerExperiment_hpp__pyplusplus_wrapper
#define vectorPlannerExperiment_hpp__pyplusplus_wrapper

void register_vectorPlannerExperiment_class();

#endif//vectorPlannerExperiment_hpp__pyplusplus_wrapper
