// This file has been generated by Py++.

#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "bindings/tools.h"
#include "vectorRunProgressData.pypp.hpp"

namespace bp = boost::python;

void register_vectorRunProgressData_class(){

    { //::std::vector< std::vector< std::map< std::string, std::string > > >
        typedef bp::class_< std::vector< std::vector< std::map< std::string, std::string > > > > vectorRunProgressData_exposer_t;
        vectorRunProgressData_exposer_t vectorRunProgressData_exposer = vectorRunProgressData_exposer_t( "vectorRunProgressData" );
        bp::scope vectorRunProgressData_scope( vectorRunProgressData_exposer );
        vectorRunProgressData_exposer.def( bp::vector_indexing_suite< ::std::vector< std::vector< std::map< std::string, std::string > > > >() );
    }

}
