// This file has been generated by Py++.

#ifndef vectorRunProgressData_hpp__pyplusplus_wrapper
#define vectorRunProgressData_hpp__pyplusplus_wrapper

void register_vectorRunProgressData_class();

#endif//vectorRunProgressData_hpp__pyplusplus_wrapper
