// This file has been generated by Py++.

#ifndef AppTypeControl_hpp__pyplusplus_wrapper
#define AppTypeControl_hpp__pyplusplus_wrapper

void register_AppTypeControl_class();

#endif//AppTypeControl_hpp__pyplusplus_wrapper
