// This file has been generated by Py++.

#ifndef GDynamicCarPlanning_hpp__pyplusplus_wrapper
#define GDynamicCarPlanning_hpp__pyplusplus_wrapper

void register_GDynamicCarPlanning_class();

#endif//GDynamicCarPlanning_hpp__pyplusplus_wrapper
