// This file has been generated by Py++.

#include "boost/python.hpp"
#include "bindings/app.h"
#include "GSE3RigidBodyPlanning.pypp.hpp"

namespace bp = boost::python;

struct GSE3RigidBodyPlanning_wrapper : ompl::app::GSE3RigidBodyPlanning, bp::wrapper< ompl::app::GSE3RigidBodyPlanning > {

    GSE3RigidBodyPlanning_wrapper( )
    : ompl::app::GSE3RigidBodyPlanning( )
      , bp::wrapper< ompl::app::GSE3RigidBodyPlanning >(){
        // null constructor
    
    }

    virtual void clear(  ) {
        if( bp::override func_clear = this->get_override( "clear" ) )
            func_clear(  );
        else{
            this->ompl::geometric::SimpleSetup::clear(  );
        }
    }
    
    void default_clear(  ) {
        ompl::geometric::SimpleSetup::clear( );
    }

    void computeGeometrySpecification(  ){
        ompl::app::RigidBodyGeometry::computeGeometrySpecification(  );
    }

    virtual ::ompl::base::ScopedState< ompl::base::StateSpace > getDefaultStartState(  ) const  {
        if( bp::override func_getDefaultStartState = this->get_override( "getDefaultStartState" ) )
            return func_getDefaultStartState(  );
        else{
            return this->ompl::app::SE3RigidBodyPlanning::getDefaultStartState(  );
        }
    }
    
    ::ompl::base::ScopedState< ompl::base::StateSpace > default_getDefaultStartState(  ) const  {
        return ompl::app::SE3RigidBodyPlanning::getDefaultStartState( );
    }

    virtual ::ompl::base::ScopedState< ompl::base::StateSpace > getFullStateFromGeometricComponent( ::ompl::base::ScopedState< ompl::base::StateSpace > const & state ) const  {
        if( bp::override func_getFullStateFromGeometricComponent = this->get_override( "getFullStateFromGeometricComponent" ) )
            return func_getFullStateFromGeometricComponent( boost::ref(state) );
        else{
            return this->ompl::app::SE3RigidBodyPlanning::getFullStateFromGeometricComponent( boost::ref(state) );
        }
    }
    
    ::ompl::base::ScopedState< ompl::base::StateSpace > default_getFullStateFromGeometricComponent( ::ompl::base::ScopedState< ompl::base::StateSpace > const & state ) const  {
        return ompl::app::SE3RigidBodyPlanning::getFullStateFromGeometricComponent( boost::ref(state) );
    }

    virtual ::ompl::base::ScopedState< ompl::base::StateSpace > getGeometricComponentState( ::ompl::base::ScopedState< ompl::base::StateSpace > const & state, unsigned int index ) const  {
        if( bp::override func_getGeometricComponentState = this->get_override( "getGeometricComponentState" ) )
            return func_getGeometricComponentState( boost::ref(state), index );
        else{
            return this->ompl::app::AppBase< (ompl::app::AppType)0 >::getGeometricComponentState( boost::ref(state), index );
        }
    }
    
    ::ompl::base::ScopedState< ompl::base::StateSpace > default_getGeometricComponentState( ::ompl::base::ScopedState< ompl::base::StateSpace > const & state, unsigned int index ) const  {
        return ompl::app::AppBase< (ompl::app::AppType)0 >::getGeometricComponentState( boost::ref(state), index );
    }

    virtual ::ompl::base::State const * getGeometricComponentStateInternal( ::ompl::base::State const * state, unsigned int arg1 ) const {
        if( bp::override func_getGeometricComponentStateInternal = this->get_override( "getGeometricComponentStateInternal" ) )
            return func_getGeometricComponentStateInternal( boost::python::ptr(state), arg1 );
        else{
            return this->ompl::app::SE3RigidBodyPlanning::getGeometricComponentStateInternal( boost::python::ptr(state), arg1 );
        }
    }
    
    virtual ::ompl::base::State const * default_getGeometricComponentStateInternal( ::ompl::base::State const * state, unsigned int arg1 ) const {
        return ompl::app::SE3RigidBodyPlanning::getGeometricComponentStateInternal( boost::python::ptr(state), arg1 );
    }

    virtual unsigned int getRobotCount(  ) const  {
        if( bp::override func_getRobotCount = this->get_override( "getRobotCount" ) )
            return func_getRobotCount(  );
        else{
            return this->ompl::app::SE3RigidBodyPlanning::getRobotCount(  );
        }
    }
    
    unsigned int default_getRobotCount(  ) const  {
        return ompl::app::SE3RigidBodyPlanning::getRobotCount( );
    }

    virtual void inferEnvironmentBounds(  ) {
        if( bp::override func_inferEnvironmentBounds = this->get_override( "inferEnvironmentBounds" ) )
            func_inferEnvironmentBounds(  );
        else{
            this->ompl::app::AppBase< (ompl::app::AppType)0 >::inferEnvironmentBounds(  );
        }
    }
    
    void default_inferEnvironmentBounds(  ) {
        ompl::app::AppBase< (ompl::app::AppType)0 >::inferEnvironmentBounds( );
    }

    virtual void inferProblemDefinitionBounds(  ) {
        if( bp::override func_inferProblemDefinitionBounds = this->get_override( "inferProblemDefinitionBounds" ) )
            func_inferProblemDefinitionBounds(  );
        else{
            this->ompl::app::AppBase< (ompl::app::AppType)0 >::inferProblemDefinitionBounds(  );
        }
    }
    
    void default_inferProblemDefinitionBounds(  ) {
        ompl::app::AppBase< (ompl::app::AppType)0 >::inferProblemDefinitionBounds( );
    }

    virtual bool isSelfCollisionEnabled(  ) const  {
        if( bp::override func_isSelfCollisionEnabled = this->get_override( "isSelfCollisionEnabled" ) )
            return func_isSelfCollisionEnabled(  );
        else{
            return this->ompl::app::SE3RigidBodyPlanning::isSelfCollisionEnabled(  );
        }
    }
    
    bool default_isSelfCollisionEnabled(  ) const  {
        return ompl::app::SE3RigidBodyPlanning::isSelfCollisionEnabled( );
    }

    virtual void setup(  ) {
        if( bp::override func_setup = this->get_override( "setup" ) )
            func_setup(  );
        else{
            this->ompl::app::AppBase< (ompl::app::AppType)0 >::setup(  );
        }
    }
    
    void default_setup(  ) {
        ompl::app::AppBase< (ompl::app::AppType)0 >::setup( );
    }

    virtual ::ompl::base::PlannerStatus solve( double time=1.0e+0 ) {
        if( bp::override func_solve = this->get_override( "solve" ) )
            return func_solve( time );
        else{
            return this->ompl::geometric::SimpleSetup::solve( time );
        }
    }
    
    ::ompl::base::PlannerStatus default_solve( double time=1.0e+0 ) {
        return ompl::geometric::SimpleSetup::solve( time );
    }

    virtual ::ompl::base::PlannerStatus solve( ::ompl::base::PlannerTerminationCondition const & ptc ) {
        if( bp::override func_solve = this->get_override( "solve" ) )
            return func_solve( boost::ref(ptc) );
        else{
            return this->ompl::geometric::SimpleSetup::solve( boost::ref(ptc) );
        }
    }
    
    ::ompl::base::PlannerStatus default_solve( ::ompl::base::PlannerTerminationCondition const & ptc ) {
        return ompl::geometric::SimpleSetup::solve( boost::ref(ptc) );
    }

};

void register_GSE3RigidBodyPlanning_class(){

    { //::ompl::app::GSE3RigidBodyPlanning
        typedef bp::class_< GSE3RigidBodyPlanning_wrapper, bp::bases< ompl::app::SE3RigidBodyPlanning, ompl::app::RenderGeometry >, boost::noncopyable > GSE3RigidBodyPlanning_exposer_t;
        GSE3RigidBodyPlanning_exposer_t GSE3RigidBodyPlanning_exposer = GSE3RigidBodyPlanning_exposer_t( "GSE3RigidBodyPlanning", bp::init< >() );
        bp::scope GSE3RigidBodyPlanning_scope( GSE3RigidBodyPlanning_exposer );
        { //::ompl::app::RigidBodyGeometry::computeGeometrySpecification
        
            typedef void ( GSE3RigidBodyPlanning_wrapper::*computeGeometrySpecification_function_type)(  ) ;
            
            GSE3RigidBodyPlanning_exposer.def( 
                "computeGeometrySpecification"
                , computeGeometrySpecification_function_type( &GSE3RigidBodyPlanning_wrapper::computeGeometrySpecification ) );
        
        }
        { //::ompl::app::SE3RigidBodyPlanning::getDefaultStartState
        
            typedef ::ompl::base::ScopedState< ompl::base::StateSpace > ( ::ompl::app::SE3RigidBodyPlanning::*getDefaultStartState_function_type)(  ) const;
            typedef ::ompl::base::ScopedState< ompl::base::StateSpace > ( GSE3RigidBodyPlanning_wrapper::*default_getDefaultStartState_function_type)(  ) const;
            
            GSE3RigidBodyPlanning_exposer.def( 
                "getDefaultStartState"
                , getDefaultStartState_function_type(&::ompl::app::SE3RigidBodyPlanning::getDefaultStartState)
                , default_getDefaultStartState_function_type(&GSE3RigidBodyPlanning_wrapper::default_getDefaultStartState) );
        
        }
        { //::ompl::app::SE3RigidBodyPlanning::getFullStateFromGeometricComponent
        
            typedef ::ompl::base::ScopedState< ompl::base::StateSpace > ( ::ompl::app::SE3RigidBodyPlanning::*getFullStateFromGeometricComponent_function_type)( ::ompl::base::ScopedState< ompl::base::StateSpace > const & ) const;
            typedef ::ompl::base::ScopedState< ompl::base::StateSpace > ( GSE3RigidBodyPlanning_wrapper::*default_getFullStateFromGeometricComponent_function_type)( ::ompl::base::ScopedState< ompl::base::StateSpace > const & ) const;
            
            GSE3RigidBodyPlanning_exposer.def( 
                "getFullStateFromGeometricComponent"
                , getFullStateFromGeometricComponent_function_type(&::ompl::app::SE3RigidBodyPlanning::getFullStateFromGeometricComponent)
                , default_getFullStateFromGeometricComponent_function_type(&GSE3RigidBodyPlanning_wrapper::default_getFullStateFromGeometricComponent)
                , ( bp::arg("state") ) );
        
        }
        { //::ompl::app::AppBase< (ompl::app::AppType)0 >::getGeometricComponentState
        
            typedef ompl::app::GSE3RigidBodyPlanning exported_class_t;
            typedef ::ompl::base::ScopedState< ompl::base::StateSpace > ( exported_class_t::*getGeometricComponentState_function_type)( ::ompl::base::ScopedState< ompl::base::StateSpace > const &,unsigned int ) const;
            typedef ::ompl::base::ScopedState< ompl::base::StateSpace > ( GSE3RigidBodyPlanning_wrapper::*default_getGeometricComponentState_function_type)( ::ompl::base::ScopedState< ompl::base::StateSpace > const &,unsigned int ) const;
            
            GSE3RigidBodyPlanning_exposer.def( 
                "getGeometricComponentState"
                , getGeometricComponentState_function_type(&::ompl::app::AppBase< (ompl::app::AppType)0 >::getGeometricComponentState)
                , default_getGeometricComponentState_function_type(&GSE3RigidBodyPlanning_wrapper::default_getGeometricComponentState)
                , ( bp::arg("state"), bp::arg("index") ) );
        
        }
        { //::ompl::app::SE3RigidBodyPlanning::getGeometricComponentStateInternal
        
            typedef ::ompl::base::State const * ( GSE3RigidBodyPlanning_wrapper::*getGeometricComponentStateInternal_function_type)( ::ompl::base::State const *,unsigned int ) const;
            
            GSE3RigidBodyPlanning_exposer.def( 
                "getGeometricComponentStateInternal"
                , getGeometricComponentStateInternal_function_type( &GSE3RigidBodyPlanning_wrapper::default_getGeometricComponentStateInternal )
                , ( bp::arg("state"), bp::arg("arg1") )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::ompl::app::SE3RigidBodyPlanning::getGeometricComponentStateSpace
        
            typedef ::ompl::base::StateSpacePtr const & ( ::ompl::app::SE3RigidBodyPlanning::*getGeometricComponentStateSpace_function_type)(  ) const;
            
            GSE3RigidBodyPlanning_exposer.def( 
                "getGeometricComponentStateSpace"
                , getGeometricComponentStateSpace_function_type(&::ompl::app::SE3RigidBodyPlanning::getGeometricComponentStateSpace)
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::ompl::app::SE3RigidBodyPlanning::getRobotCount
        
            typedef unsigned int ( ::ompl::app::SE3RigidBodyPlanning::*getRobotCount_function_type)(  ) const;
            typedef unsigned int ( GSE3RigidBodyPlanning_wrapper::*default_getRobotCount_function_type)(  ) const;
            
            GSE3RigidBodyPlanning_exposer.def( 
                "getRobotCount"
                , getRobotCount_function_type(&::ompl::app::SE3RigidBodyPlanning::getRobotCount)
                , default_getRobotCount_function_type(&GSE3RigidBodyPlanning_wrapper::default_getRobotCount) );
        
        }
        { //::ompl::app::AppBase< (ompl::app::AppType)0 >::inferEnvironmentBounds
        
            typedef ompl::app::GSE3RigidBodyPlanning exported_class_t;
            typedef void ( exported_class_t::*inferEnvironmentBounds_function_type)(  ) ;
            typedef void ( GSE3RigidBodyPlanning_wrapper::*default_inferEnvironmentBounds_function_type)(  ) ;
            
            GSE3RigidBodyPlanning_exposer.def( 
                "inferEnvironmentBounds"
                , inferEnvironmentBounds_function_type(&::ompl::app::AppBase< (ompl::app::AppType)0 >::inferEnvironmentBounds)
                , default_inferEnvironmentBounds_function_type(&GSE3RigidBodyPlanning_wrapper::default_inferEnvironmentBounds) );
        
        }
        { //::ompl::app::AppBase< (ompl::app::AppType)0 >::inferProblemDefinitionBounds
        
            typedef ompl::app::GSE3RigidBodyPlanning exported_class_t;
            typedef void ( exported_class_t::*inferProblemDefinitionBounds_function_type)(  ) ;
            typedef void ( GSE3RigidBodyPlanning_wrapper::*default_inferProblemDefinitionBounds_function_type)(  ) ;
            
            GSE3RigidBodyPlanning_exposer.def( 
                "inferProblemDefinitionBounds"
                , inferProblemDefinitionBounds_function_type(&::ompl::app::AppBase< (ompl::app::AppType)0 >::inferProblemDefinitionBounds)
                , default_inferProblemDefinitionBounds_function_type(&GSE3RigidBodyPlanning_wrapper::default_inferProblemDefinitionBounds) );
        
        }
        { //::ompl::app::SE3RigidBodyPlanning::isSelfCollisionEnabled
        
            typedef bool ( ::ompl::app::SE3RigidBodyPlanning::*isSelfCollisionEnabled_function_type)(  ) const;
            typedef bool ( GSE3RigidBodyPlanning_wrapper::*default_isSelfCollisionEnabled_function_type)(  ) const;
            
            GSE3RigidBodyPlanning_exposer.def( 
                "isSelfCollisionEnabled"
                , isSelfCollisionEnabled_function_type(&::ompl::app::SE3RigidBodyPlanning::isSelfCollisionEnabled)
                , default_isSelfCollisionEnabled_function_type(&GSE3RigidBodyPlanning_wrapper::default_isSelfCollisionEnabled) );
        
        }
        { //::ompl::app::AppBase< (ompl::app::AppType)0 >::setup
        
            typedef ompl::app::GSE3RigidBodyPlanning exported_class_t;
            typedef void ( exported_class_t::*setup_function_type)(  ) ;
            typedef void ( GSE3RigidBodyPlanning_wrapper::*default_setup_function_type)(  ) ;
            
            GSE3RigidBodyPlanning_exposer.def( 
                "setup"
                , setup_function_type(&::ompl::app::AppBase< (ompl::app::AppType)0 >::setup)
                , default_setup_function_type(&GSE3RigidBodyPlanning_wrapper::default_setup) );
        
        }
        GSE3RigidBodyPlanning_exposer.def("solve", (::ompl::base::PlannerStatus(::ompl::app::GSE3RigidBodyPlanning::*)( double ))(&::ompl::app::GSE3RigidBodyPlanning::solve), (bp::arg("solveTime")) );
        GSE3RigidBodyPlanning_exposer.def("solve", (::ompl::base::PlannerStatus(::ompl::app::GSE3RigidBodyPlanning::*)( const ompl::base::PlannerTerminationCondition& ))(&::ompl::app::GSE3RigidBodyPlanning::solve), (bp::arg("ptc")) );
        GSE3RigidBodyPlanning_exposer.def("clear", &GSE3RigidBodyPlanning_wrapper::clear);
        GSE3RigidBodyPlanning_exposer.def("getStateSpace", &::ompl::geometric::SimpleSetup::getStateSpace, bp::return_value_policy< bp::copy_const_reference >());
    }

}
