// This file has been generated by Py++.

#ifndef GSE3RigidBodyPlanning_hpp__pyplusplus_wrapper
#define GSE3RigidBodyPlanning_hpp__pyplusplus_wrapper

void register_GSE3RigidBodyPlanning_class();

#endif//GSE3RigidBodyPlanning_hpp__pyplusplus_wrapper
