// This file has been generated by Py++.

#ifndef KinematicCarPlanning_hpp__pyplusplus_wrapper
#define KinematicCarPlanning_hpp__pyplusplus_wrapper

void register_KinematicCarPlanning_class();

#endif//KinematicCarPlanning_hpp__pyplusplus_wrapper
