// This file has been generated by Py++.

#include "boost/python.hpp"
#include "bindings/app.h"
#include "RenderGeometry.pypp.hpp"

namespace bp = boost::python;

void register_RenderGeometry_class(){

    { //::ompl::app::RenderGeometry
        typedef bp::class_< ompl::app::RenderGeometry, boost::noncopyable > RenderGeometry_exposer_t;
        RenderGeometry_exposer_t RenderGeometry_exposer = RenderGeometry_exposer_t( "RenderGeometry", bp::init< ompl::app::RigidBodyGeometry const &, ompl::app::GeometricStateExtractor const & >(( bp::arg("rbg"), bp::arg("se") )) );
        bp::scope RenderGeometry_scope( RenderGeometry_exposer );
        { //::ompl::app::RenderGeometry::renderEnvironment
        
            typedef int ( ::ompl::app::RenderGeometry::*renderEnvironment_function_type)(  ) const;
            
            RenderGeometry_exposer.def( 
                "renderEnvironment"
                , renderEnvironment_function_type( &::ompl::app::RenderGeometry::renderEnvironment ) );
        
        }
        { //::ompl::app::RenderGeometry::renderPlannerData
        
            typedef int ( ::ompl::app::RenderGeometry::*renderPlannerData_function_type)( ::ompl::base::PlannerData const & ) const;
            
            RenderGeometry_exposer.def( 
                "renderPlannerData"
                , renderPlannerData_function_type( &::ompl::app::RenderGeometry::renderPlannerData )
                , ( bp::arg("pd") ) );
        
        }
        { //::ompl::app::RenderGeometry::renderRobot
        
            typedef int ( ::ompl::app::RenderGeometry::*renderRobot_function_type)(  ) const;
            
            RenderGeometry_exposer.def( 
                "renderRobot"
                , renderRobot_function_type( &::ompl::app::RenderGeometry::renderRobot ) );
        
        }
        { //::ompl::app::RenderGeometry::renderRobotPart
        
            typedef int ( ::ompl::app::RenderGeometry::*renderRobotPart_function_type)( unsigned int ) const;
            
            RenderGeometry_exposer.def( 
                "renderRobotPart"
                , renderRobotPart_function_type( &::ompl::app::RenderGeometry::renderRobotPart )
                , ( bp::arg("index") ) );
        
        }
    }

}
