// This file has been generated by Py++.

#ifndef RigidBodyGeometry_hpp__pyplusplus_wrapper
#define RigidBodyGeometry_hpp__pyplusplus_wrapper

void register_RigidBodyGeometry_class();

#endif//RigidBodyGeometry_hpp__pyplusplus_wrapper
