// This file has been generated by Py++.

#ifndef SE3MultiRigidBodyPlanning_hpp__pyplusplus_wrapper
#define SE3MultiRigidBodyPlanning_hpp__pyplusplus_wrapper

void register_SE3MultiRigidBodyPlanning_class();

#endif//SE3MultiRigidBodyPlanning_hpp__pyplusplus_wrapper
