// This file has been generated by Py++.

#ifndef SE3RigidBodyPlanning_hpp__pyplusplus_wrapper
#define SE3RigidBodyPlanning_hpp__pyplusplus_wrapper

void register_SE3RigidBodyPlanning_class();

#endif//SE3RigidBodyPlanning_hpp__pyplusplus_wrapper
