// This file has been generated by Py++.

#include "boost/python.hpp"
#include "bindings/base.h"
#include "_base_enumerations.pypp.hpp"

namespace bp = boost::python;

void register_enumerations(){

    bp::enum_< ompl::base::AdvancedStateCopyOperation>("AdvancedStateCopyOperation")
        .value("NO_DATA_COPIED", ompl::base::NO_DATA_COPIED)
        .value("SOME_DATA_COPIED", ompl::base::SOME_DATA_COPIED)
        .value("ALL_DATA_COPIED", ompl::base::ALL_DATA_COPIED)
        .export_values()
        ;

    bp::enum_< ompl::base::GoalType>("GoalType")
        .value("GOAL_ANY", ompl::base::GOAL_ANY)
        .value("GOAL_REGION", ompl::base::GOAL_REGION)
        .value("GOAL_SAMPLEABLE_REGION", ompl::base::GOAL_SAMPLEABLE_REGION)
        .value("GOAL_STATE", ompl::base::GOAL_STATE)
        .value("GOAL_STATES", ompl::base::GOAL_STATES)
        .value("GOAL_LAZY_SAMPLES", ompl::base::GOAL_LAZY_SAMPLES)
        .export_values()
        ;

    bp::enum_< ompl::base::StateSpaceType>("StateSpaceType")
        .value("STATE_SPACE_UNKNOWN", ompl::base::STATE_SPACE_UNKNOWN)
        .value("STATE_SPACE_REAL_VECTOR", ompl::base::STATE_SPACE_REAL_VECTOR)
        .value("STATE_SPACE_SO2", ompl::base::STATE_SPACE_SO2)
        .value("STATE_SPACE_SO3", ompl::base::STATE_SPACE_SO3)
        .value("STATE_SPACE_SE2", ompl::base::STATE_SPACE_SE2)
        .value("STATE_SPACE_SE3", ompl::base::STATE_SPACE_SE3)
        .value("STATE_SPACE_TIME", ompl::base::STATE_SPACE_TIME)
        .value("STATE_SPACE_DISCRETE", ompl::base::STATE_SPACE_DISCRETE)
        .value("STATE_SPACE_TYPE_COUNT", ompl::base::STATE_SPACE_TYPE_COUNT)
        .export_values()
        ;

}
