// This file has been generated by Py++.

#ifndef _SubstateLocation__value_traits_pypp_hpp_hpp__pyplusplus_wrapper
#define _SubstateLocation__value_traits_pypp_hpp_hpp__pyplusplus_wrapper

namespace boost { namespace python { namespace indexing {

template<>
struct value_traits< ompl::base::StateSpace::SubstateLocation >{

    static bool const equality_comparable = false;
    

    static bool const less_than_comparable = false;
    

    template<typename PythonClass, typename Policy>
    static void visit_container_class(PythonClass &, Policy const &){
        
    }

};

}/*indexing*/ } /*python*/ } /*boost*/

#endif//_SubstateLocation__value_traits_pypp_hpp_hpp__pyplusplus_wrapper
