// This file has been generated by Py++.

#ifndef AbstractState_hpp__pyplusplus_wrapper
#define AbstractState_hpp__pyplusplus_wrapper

void register_AbstractState_class();

#endif//AbstractState_hpp__pyplusplus_wrapper
