// This file has been generated by Py++.

#ifndef CompoundStateSpace_hpp__pyplusplus_wrapper
#define CompoundStateSpace_hpp__pyplusplus_wrapper

void register_CompoundStateSpace_class();

#endif//CompoundStateSpace_hpp__pyplusplus_wrapper
