// This file has been generated by Py++.

#ifndef DubinsStateSpace_hpp__pyplusplus_wrapper
#define DubinsStateSpace_hpp__pyplusplus_wrapper

void register_DubinsStateSpace_class();

#endif//DubinsStateSpace_hpp__pyplusplus_wrapper
