// This file has been generated by Py++.

#include "boost/python.hpp"
#include "bindings/base.h"
#include "DubinsState.pypp.hpp"

namespace bp = boost::python;

double __getitem(::ompl::base::ScopedState<ompl::base::DubinsStateSpace>* obj, unsigned int i)
{
    return (*obj)[i];
}

void __setitem(::ompl::base::ScopedState<ompl::base::DubinsStateSpace>* obj, unsigned int i, double val)
{
    (*obj)[i] = val;
}

std::string __str__(::ompl::base::ScopedState<ompl::base::DubinsStateSpace>* obj)
{
    std::ostringstream s;
    obj->print(s);
    return s.str();
}

void register_DubinsState_class(){

    { //::ompl::base::ScopedState< ompl::base::DubinsStateSpace >
        typedef bp::class_< ompl::base::ScopedState< ompl::base::DubinsStateSpace > > DubinsState_exposer_t;
        DubinsState_exposer_t DubinsState_exposer = DubinsState_exposer_t( "DubinsState", bp::init< boost::shared_ptr< ompl::base::SpaceInformation > const & >(( bp::arg("si") )) );
        bp::scope DubinsState_scope( DubinsState_exposer );
        bp::implicitly_convertible< boost::shared_ptr< ompl::base::SpaceInformation > const &, ompl::base::ScopedState< ompl::base::DubinsStateSpace > >();
        DubinsState_exposer.def( bp::init< boost::shared_ptr< ompl::base::StateSpace > const & >(( bp::arg("space") )) );
        bp::implicitly_convertible< boost::shared_ptr< ompl::base::StateSpace > const &, ompl::base::ScopedState< ompl::base::DubinsStateSpace > >();
        DubinsState_exposer.def( bp::init< ompl::base::ScopedState< ompl::base::DubinsStateSpace > const & >(( bp::arg("other") )) );
        DubinsState_exposer.def( bp::init< boost::shared_ptr< ompl::base::StateSpace > const &, ompl::base::State const * >(( bp::arg("space"), bp::arg("state") )) );
        { //::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::distance
        
            typedef ompl::base::ScopedState< ompl::base::DubinsStateSpace > exported_class_t;
            typedef double ( exported_class_t::*distance_function_type)( ::ompl::base::State const * ) const;
            
            DubinsState_exposer.def( 
                "distance"
                , distance_function_type( &::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::distance )
                , ( bp::arg("state") ) );
        
        }
        { //::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::enforceBounds
        
            typedef ompl::base::ScopedState< ompl::base::DubinsStateSpace > exported_class_t;
            typedef void ( exported_class_t::*enforceBounds_function_type)(  ) ;
            
            DubinsState_exposer.def( 
                "enforceBounds"
                , enforceBounds_function_type( &::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::enforceBounds ) );
        
        }
        { //::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::get
        
            typedef ompl::base::ScopedState< ompl::base::DubinsStateSpace > exported_class_t;
            typedef ::ompl::base::SE2StateSpace::StateType * ( exported_class_t::*get_function_type)(  ) ;
            
            DubinsState_exposer.def( 
                "get"
                , get_function_type( &::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::get )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::get
        
            typedef ompl::base::ScopedState< ompl::base::DubinsStateSpace > exported_class_t;
            typedef ::ompl::base::SE2StateSpace::StateType const * ( exported_class_t::*get_function_type)(  ) const;
            
            DubinsState_exposer.def( 
                "get"
                , get_function_type( &::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::get )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::getSpace
        
            typedef ompl::base::ScopedState< ompl::base::DubinsStateSpace > exported_class_t;
            typedef ::boost::shared_ptr< ompl::base::StateSpace > const & ( exported_class_t::*getSpace_function_type)(  ) const;
            
            DubinsState_exposer.def( 
                "getSpace"
                , getSpace_function_type( &::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::getSpace )
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::operator()
        
            typedef ompl::base::ScopedState< ompl::base::DubinsStateSpace > exported_class_t;
            typedef ::ompl::base::SE2StateSpace::StateType * ( exported_class_t::*__call___function_type)(  ) const;
            
            DubinsState_exposer.def( 
                "__call__"
                , __call___function_type( &::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::operator() )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::operator=
        
            typedef ompl::base::ScopedState< ompl::base::DubinsStateSpace > exported_class_t;
            typedef ::ompl::base::ScopedState< ompl::base::DubinsStateSpace > & ( exported_class_t::*assign_function_type)( ::ompl::base::ScopedState< ompl::base::DubinsStateSpace > const & ) ;
            
            DubinsState_exposer.def( 
                "assign"
                , assign_function_type( &::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::operator= )
                , ( bp::arg("other") )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::operator=
        
            typedef ompl::base::ScopedState< ompl::base::DubinsStateSpace > exported_class_t;
            typedef ::ompl::base::ScopedState< ompl::base::DubinsStateSpace > & ( exported_class_t::*assign_function_type)( ::ompl::base::State const * ) ;
            
            DubinsState_exposer.def( 
                "assign"
                , assign_function_type( &::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::operator= )
                , ( bp::arg("other") )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::operator=
        
            typedef ompl::base::ScopedState< ompl::base::DubinsStateSpace > exported_class_t;
            typedef ::ompl::base::ScopedState< ompl::base::DubinsStateSpace > & ( exported_class_t::*assign_function_type)( ::std::vector< double > const & ) ;
            
            DubinsState_exposer.def( 
                "assign"
                , assign_function_type( &::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::operator= )
                , ( bp::arg("reals") )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::operator=
        
            typedef ompl::base::ScopedState< ompl::base::DubinsStateSpace > exported_class_t;
            typedef ::ompl::base::ScopedState< ompl::base::DubinsStateSpace > & ( exported_class_t::*assign_function_type)( double const ) ;
            
            DubinsState_exposer.def( 
                "assign"
                , assign_function_type( &::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::operator= )
                , ( bp::arg("value") )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::random
        
            typedef ompl::base::ScopedState< ompl::base::DubinsStateSpace > exported_class_t;
            typedef void ( exported_class_t::*random_function_type)(  ) ;
            
            DubinsState_exposer.def( 
                "random"
                , random_function_type( &::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::random ) );
        
        }
        { //::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::reals
        
            typedef ompl::base::ScopedState< ompl::base::DubinsStateSpace > exported_class_t;
            typedef ::std::vector< double > ( exported_class_t::*reals_function_type)(  ) const;
            
            DubinsState_exposer.def( 
                "reals"
                , reals_function_type( &::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::reals ) );
        
        }
        { //::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::satisfiesBounds
        
            typedef ompl::base::ScopedState< ompl::base::DubinsStateSpace > exported_class_t;
            typedef bool ( exported_class_t::*satisfiesBounds_function_type)(  ) const;
            
            DubinsState_exposer.def( 
                "satisfiesBounds"
                , satisfiesBounds_function_type( &::ompl::base::ScopedState< ompl::base::DubinsStateSpace >::satisfiesBounds ) );
        
        }
        DubinsState_exposer.def(bp::init<ompl::base::ScopedState<ompl::base::StateSpace> const &>(( bp::arg("other") )));
        DubinsState_exposer.def("__getitem__", &__getitem);
        DubinsState_exposer.def("__setitem__", &__setitem);
        DubinsState_exposer.def("__str__", &__str__);
    }

}
