// This file has been generated by Py++.

#ifndef EuclideanProjection_hpp__pyplusplus_wrapper
#define EuclideanProjection_hpp__pyplusplus_wrapper

void register_EuclideanProjection_class();

#endif//EuclideanProjection_hpp__pyplusplus_wrapper
