// This file has been generated by Py++.

#ifndef GenericParam_hpp__pyplusplus_wrapper
#define GenericParam_hpp__pyplusplus_wrapper

void register_GenericParam_class();

#endif//GenericParam_hpp__pyplusplus_wrapper
