// This file has been generated by Py++.

#ifndef GoalRegion_hpp__pyplusplus_wrapper
#define GoalRegion_hpp__pyplusplus_wrapper

void register_GoalRegion_class();

#endif//GoalRegion_hpp__pyplusplus_wrapper
