// This file has been generated by Py++.

#ifndef mapStringToGenericParam_hpp__pyplusplus_wrapper
#define mapStringToGenericParam_hpp__pyplusplus_wrapper

void register_mapStringToGenericParam_class();

#endif//mapStringToGenericParam_hpp__pyplusplus_wrapper
