// This file has been generated by Py++.

#ifndef MaximizeClearanceValidStateSampler_hpp__pyplusplus_wrapper
#define MaximizeClearanceValidStateSampler_hpp__pyplusplus_wrapper

void register_MaximizeClearanceValidStateSampler_class();

#endif//MaximizeClearanceValidStateSampler_hpp__pyplusplus_wrapper
