// This file has been generated by Py++.

#ifndef MultiOptimizationObjective_hpp__pyplusplus_wrapper
#define MultiOptimizationObjective_hpp__pyplusplus_wrapper

void register_MultiOptimizationObjective_class();

#endif//MultiOptimizationObjective_hpp__pyplusplus_wrapper
