// This file has been generated by Py++.

#ifndef PlannerSolution_hpp__pyplusplus_wrapper
#define PlannerSolution_hpp__pyplusplus_wrapper

void register_PlannerSolution_class();

#endif//PlannerSolution_hpp__pyplusplus_wrapper
