// This file has been generated by Py++.

#ifndef PlannerTerminationCondition_hpp__pyplusplus_wrapper
#define PlannerTerminationCondition_hpp__pyplusplus_wrapper

void register_PlannerTerminationCondition_class();

#endif//PlannerTerminationCondition_hpp__pyplusplus_wrapper
