// This file has been generated by Py++.

#ifndef PlannerDataVertex_hpp__pyplusplus_wrapper
#define PlannerDataVertex_hpp__pyplusplus_wrapper

void register_PlannerDataVertex_class();

#endif//PlannerDataVertex_hpp__pyplusplus_wrapper
