// This file has been generated by Py++.

#ifndef ProblemDefinition_hpp__pyplusplus_wrapper
#define ProblemDefinition_hpp__pyplusplus_wrapper

void register_ProblemDefinition_class();

#endif//ProblemDefinition_hpp__pyplusplus_wrapper
