// This file has been generated by Py++.

#ifndef ProjectionEvaluator_hpp__pyplusplus_wrapper
#define ProjectionEvaluator_hpp__pyplusplus_wrapper

void register_ProjectionEvaluator_class();

#endif//ProjectionEvaluator_hpp__pyplusplus_wrapper
