// This file has been generated by Py++.

#ifndef ProjectionMatrix_hpp__pyplusplus_wrapper
#define ProjectionMatrix_hpp__pyplusplus_wrapper

void register_ProjectionMatrix_class();

#endif//ProjectionMatrix_hpp__pyplusplus_wrapper
