// This file has been generated by Py++.

#ifndef RealVectorStateSampler_hpp__pyplusplus_wrapper
#define RealVectorStateSampler_hpp__pyplusplus_wrapper

void register_RealVectorStateSampler_class();

#endif//RealVectorStateSampler_hpp__pyplusplus_wrapper
