// This file has been generated by Py++.

#include "boost/python.hpp"
#include "bindings/base.h"
#include "ReedsSheppMotionValidator.pypp.hpp"

namespace bp = boost::python;

struct ReedsSheppMotionValidator_wrapper : ompl::base::ReedsSheppMotionValidator, bp::wrapper< ompl::base::ReedsSheppMotionValidator > {

    ReedsSheppMotionValidator_wrapper(ompl::base::ReedsSheppMotionValidator const & arg )
    : ompl::base::ReedsSheppMotionValidator( arg )
      , bp::wrapper< ompl::base::ReedsSheppMotionValidator >(){
        // copy constructor
        
    }

    ReedsSheppMotionValidator_wrapper(::ompl::base::SpaceInformation * si )
    : ompl::base::ReedsSheppMotionValidator( boost::python::ptr(si) )
      , bp::wrapper< ompl::base::ReedsSheppMotionValidator >(){
        // constructor
    
    }

    ReedsSheppMotionValidator_wrapper(::ompl::base::SpaceInformationPtr const & si )
    : ompl::base::ReedsSheppMotionValidator( si )
      , bp::wrapper< ompl::base::ReedsSheppMotionValidator >(){
        // constructor
    
    }

    virtual bool checkMotion( ::ompl::base::State const * s1, ::ompl::base::State const * s2 ) const  {
        if( bp::override func_checkMotion = this->get_override( "checkMotion" ) )
            return func_checkMotion( boost::python::ptr(s1), boost::python::ptr(s2) );
        else{
            return this->ompl::base::ReedsSheppMotionValidator::checkMotion( boost::python::ptr(s1), boost::python::ptr(s2) );
        }
    }
    
    bool default_checkMotion( ::ompl::base::State const * s1, ::ompl::base::State const * s2 ) const  {
        return ompl::base::ReedsSheppMotionValidator::checkMotion( boost::python::ptr(s1), boost::python::ptr(s2) );
    }

    virtual bool checkMotion( ::ompl::base::State const * s1, ::ompl::base::State const * s2, ::std::pair< ompl::base::State*, double > & lastValid ) const  {
        if( bp::override func_checkMotion = this->get_override( "checkMotion" ) )
            return func_checkMotion( boost::python::ptr(s1), boost::python::ptr(s2), boost::ref(lastValid) );
        else{
            return this->ompl::base::ReedsSheppMotionValidator::checkMotion( boost::python::ptr(s1), boost::python::ptr(s2), boost::ref(lastValid) );
        }
    }
    
    bool default_checkMotion( ::ompl::base::State const * s1, ::ompl::base::State const * s2, ::std::pair< ompl::base::State*, double > & lastValid ) const  {
        return ompl::base::ReedsSheppMotionValidator::checkMotion( boost::python::ptr(s1), boost::python::ptr(s2), boost::ref(lastValid) );
    }

};

void register_ReedsSheppMotionValidator_class(){

    { //::ompl::base::ReedsSheppMotionValidator
        typedef bp::class_< ReedsSheppMotionValidator_wrapper, bp::bases< ompl::base::MotionValidator > > ReedsSheppMotionValidator_exposer_t;
        ReedsSheppMotionValidator_exposer_t ReedsSheppMotionValidator_exposer = ReedsSheppMotionValidator_exposer_t( "ReedsSheppMotionValidator", bp::init< ompl::base::SpaceInformation * >(( bp::arg("si") )) );
        bp::scope ReedsSheppMotionValidator_scope( ReedsSheppMotionValidator_exposer );
        bp::implicitly_convertible< ompl::base::SpaceInformation *, ompl::base::ReedsSheppMotionValidator >();
        ReedsSheppMotionValidator_exposer.def( bp::init< ompl::base::SpaceInformationPtr const & >(( bp::arg("si") )) );
        bp::implicitly_convertible< ompl::base::SpaceInformationPtr const &, ompl::base::ReedsSheppMotionValidator >();
        { //::ompl::base::ReedsSheppMotionValidator::checkMotion
        
            typedef bool ( ::ompl::base::ReedsSheppMotionValidator::*checkMotion_function_type)( ::ompl::base::State const *,::ompl::base::State const * ) const;
            typedef bool ( ReedsSheppMotionValidator_wrapper::*default_checkMotion_function_type)( ::ompl::base::State const *,::ompl::base::State const * ) const;
            
            ReedsSheppMotionValidator_exposer.def( 
                "checkMotion"
                , checkMotion_function_type(&::ompl::base::ReedsSheppMotionValidator::checkMotion)
                , default_checkMotion_function_type(&ReedsSheppMotionValidator_wrapper::default_checkMotion)
                , ( bp::arg("s1"), bp::arg("s2") ) );
        
        }
        { //::ompl::base::ReedsSheppMotionValidator::checkMotion
        
            typedef bool ( ::ompl::base::ReedsSheppMotionValidator::*checkMotion_function_type)( ::ompl::base::State const *,::ompl::base::State const *,::std::pair< ompl::base::State*, double > & ) const;
            typedef bool ( ReedsSheppMotionValidator_wrapper::*default_checkMotion_function_type)( ::ompl::base::State const *,::ompl::base::State const *,::std::pair< ompl::base::State*, double > & ) const;
            
            ReedsSheppMotionValidator_exposer.def( 
                "checkMotion"
                , checkMotion_function_type(&::ompl::base::ReedsSheppMotionValidator::checkMotion)
                , default_checkMotion_function_type(&ReedsSheppMotionValidator_wrapper::default_checkMotion)
                , ( bp::arg("s1"), bp::arg("s2"), bp::arg("lastValid") ) );
        
        }
    }

}
