// This file has been generated by Py++.

#ifndef SO2StateSpace_hpp__pyplusplus_wrapper
#define SO2StateSpace_hpp__pyplusplus_wrapper

void register_SO2StateSpace_class();

#endif//SO2StateSpace_hpp__pyplusplus_wrapper
