// This file has been generated by Py++.

#ifndef SO2StateSampler_hpp__pyplusplus_wrapper
#define SO2StateSampler_hpp__pyplusplus_wrapper

void register_SO2StateSampler_class();

#endif//SO2StateSampler_hpp__pyplusplus_wrapper
