// This file has been generated by Py++.

#ifndef SO3StateSpace_hpp__pyplusplus_wrapper
#define SO3StateSpace_hpp__pyplusplus_wrapper

void register_SO3StateSpace_class();

#endif//SO3StateSpace_hpp__pyplusplus_wrapper
