// This file has been generated by Py++.

#ifndef SO3StateSampler_hpp__pyplusplus_wrapper
#define SO3StateSampler_hpp__pyplusplus_wrapper

void register_SO3StateSampler_class();

#endif//SO3StateSampler_hpp__pyplusplus_wrapper
