// This file has been generated by Py++.

#ifndef SpecificParamFloat_hpp__pyplusplus_wrapper
#define SpecificParamFloat_hpp__pyplusplus_wrapper

void register_SpecificParamFloat_class();

#endif//SpecificParamFloat_hpp__pyplusplus_wrapper
