// This file has been generated by Py++.

#ifndef StateValidityChecker_hpp__pyplusplus_wrapper
#define StateValidityChecker_hpp__pyplusplus_wrapper

void register_StateValidityChecker_class();

#endif//StateValidityChecker_hpp__pyplusplus_wrapper
