// This file has been generated by Py++.

#ifndef StateCostIntegralObjective_hpp__pyplusplus_wrapper
#define StateCostIntegralObjective_hpp__pyplusplus_wrapper

void register_StateCostIntegralObjective_class();

#endif//StateCostIntegralObjective_hpp__pyplusplus_wrapper
