// This file has been generated by Py++.

#include "boost/python.hpp"
#include "bindings/base.h"
#include "StateValidityChecker.pypp.hpp"

namespace bp = boost::python;

struct StateValidityChecker_wrapper : ompl::base::StateValidityChecker, bp::wrapper< ompl::base::StateValidityChecker > {

    StateValidityChecker_wrapper(::ompl::base::SpaceInformation * si )
    : ompl::base::StateValidityChecker( boost::python::ptr(si) )
      , bp::wrapper< ompl::base::StateValidityChecker >(){
        // constructor
    
    }

    StateValidityChecker_wrapper(::ompl::base::SpaceInformationPtr const & si )
    : ompl::base::StateValidityChecker( si )
      , bp::wrapper< ompl::base::StateValidityChecker >(){
        // constructor
    
    }

    virtual double clearance( ::ompl::base::State const * arg0 ) const  {
        if( bp::override func_clearance = this->get_override( "clearance" ) )
            return func_clearance( boost::python::ptr(arg0) );
        else{
            return this->ompl::base::StateValidityChecker::clearance( boost::python::ptr(arg0) );
        }
    }
    
    double default_clearance( ::ompl::base::State const * arg0 ) const  {
        return ompl::base::StateValidityChecker::clearance( boost::python::ptr(arg0) );
    }

    virtual double clearance( ::ompl::base::State const * state, ::ompl::base::State * arg1, bool & validStateAvailable ) const  {
        if( bp::override func_clearance = this->get_override( "clearance" ) )
            return func_clearance( boost::python::ptr(state), boost::python::ptr(arg1), validStateAvailable );
        else{
            return this->ompl::base::StateValidityChecker::clearance( boost::python::ptr(state), boost::python::ptr(arg1), validStateAvailable );
        }
    }
    
    double default_clearance( ::ompl::base::State const * state, ::ompl::base::State * arg1, bool & validStateAvailable ) const  {
        return ompl::base::StateValidityChecker::clearance( boost::python::ptr(state), boost::python::ptr(arg1), validStateAvailable );
    }

    virtual bool isValid( ::ompl::base::State const * state ) const {
        bp::override func_isValid = this->get_override( "isValid" );
        return func_isValid( boost::python::ptr(state) );
    }

    virtual bool isValid( ::ompl::base::State const * state, double & dist ) const  {
        if( bp::override func_isValid = this->get_override( "isValid" ) )
            return func_isValid( boost::python::ptr(state), dist );
        else{
            return this->ompl::base::StateValidityChecker::isValid( boost::python::ptr(state), dist );
        }
    }
    
    bool default_isValid( ::ompl::base::State const * state, double & dist ) const  {
        return ompl::base::StateValidityChecker::isValid( boost::python::ptr(state), dist );
    }

    virtual bool isValid( ::ompl::base::State const * state, double & dist, ::ompl::base::State * validState, bool & validStateAvailable ) const  {
        if( bp::override func_isValid = this->get_override( "isValid" ) )
            return func_isValid( boost::python::ptr(state), dist, boost::python::ptr(validState), validStateAvailable );
        else{
            return this->ompl::base::StateValidityChecker::isValid( boost::python::ptr(state), dist, boost::python::ptr(validState), validStateAvailable );
        }
    }
    
    bool default_isValid( ::ompl::base::State const * state, double & dist, ::ompl::base::State * validState, bool & validStateAvailable ) const  {
        return ompl::base::StateValidityChecker::isValid( boost::python::ptr(state), dist, boost::python::ptr(validState), validStateAvailable );
    }

};

void register_StateValidityChecker_class(){

    { //::ompl::base::StateValidityChecker
        typedef bp::class_< StateValidityChecker_wrapper, boost::noncopyable > StateValidityChecker_exposer_t;
        StateValidityChecker_exposer_t StateValidityChecker_exposer = StateValidityChecker_exposer_t( "StateValidityChecker", bp::init< ompl::base::SpaceInformation * >(( bp::arg("si") )) );
        bp::scope StateValidityChecker_scope( StateValidityChecker_exposer );
        StateValidityChecker_exposer.def( bp::init< ompl::base::SpaceInformationPtr const & >(( bp::arg("si") )) );
        { //::ompl::base::StateValidityChecker::clearance
        
            typedef double ( ::ompl::base::StateValidityChecker::*clearance_function_type)( ::ompl::base::State const * ) const;
            typedef double ( StateValidityChecker_wrapper::*default_clearance_function_type)( ::ompl::base::State const * ) const;
            
            StateValidityChecker_exposer.def( 
                "clearance"
                , clearance_function_type(&::ompl::base::StateValidityChecker::clearance)
                , default_clearance_function_type(&StateValidityChecker_wrapper::default_clearance)
                , ( bp::arg("arg0") ) );
        
        }
        { //::ompl::base::StateValidityChecker::clearance
        
            typedef double ( ::ompl::base::StateValidityChecker::*clearance_function_type)( ::ompl::base::State const *,::ompl::base::State *,bool & ) const;
            typedef double ( StateValidityChecker_wrapper::*default_clearance_function_type)( ::ompl::base::State const *,::ompl::base::State *,bool & ) const;
            
            StateValidityChecker_exposer.def( 
                "clearance"
                , clearance_function_type(&::ompl::base::StateValidityChecker::clearance)
                , default_clearance_function_type(&StateValidityChecker_wrapper::default_clearance)
                , ( bp::arg("state"), bp::arg("arg1"), bp::arg("validStateAvailable") ) );
        
        }
        { //::ompl::base::StateValidityChecker::getSpecs
        
            typedef ::ompl::base::StateValidityCheckerSpecs const & ( ::ompl::base::StateValidityChecker::*getSpecs_function_type)(  ) const;
            
            StateValidityChecker_exposer.def( 
                "getSpecs"
                , getSpecs_function_type( &::ompl::base::StateValidityChecker::getSpecs )
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::ompl::base::StateValidityChecker::isValid
        
            typedef bool ( ::ompl::base::StateValidityChecker::*isValid_function_type)( ::ompl::base::State const * ) const;
            
            StateValidityChecker_exposer.def( 
                "isValid"
                , bp::pure_virtual( isValid_function_type(&::ompl::base::StateValidityChecker::isValid) )
                , ( bp::arg("state") ) );
        
        }
        { //::ompl::base::StateValidityChecker::isValid
        
            typedef bool ( ::ompl::base::StateValidityChecker::*isValid_function_type)( ::ompl::base::State const *,double & ) const;
            typedef bool ( StateValidityChecker_wrapper::*default_isValid_function_type)( ::ompl::base::State const *,double & ) const;
            
            StateValidityChecker_exposer.def( 
                "isValid"
                , isValid_function_type(&::ompl::base::StateValidityChecker::isValid)
                , default_isValid_function_type(&StateValidityChecker_wrapper::default_isValid)
                , ( bp::arg("state"), bp::arg("dist") ) );
        
        }
        { //::ompl::base::StateValidityChecker::isValid
        
            typedef bool ( ::ompl::base::StateValidityChecker::*isValid_function_type)( ::ompl::base::State const *,double &,::ompl::base::State *,bool & ) const;
            typedef bool ( StateValidityChecker_wrapper::*default_isValid_function_type)( ::ompl::base::State const *,double &,::ompl::base::State *,bool & ) const;
            
            StateValidityChecker_exposer.def( 
                "isValid"
                , isValid_function_type(&::ompl::base::StateValidityChecker::isValid)
                , default_isValid_function_type(&StateValidityChecker_wrapper::default_isValid)
                , ( bp::arg("state"), bp::arg("dist"), bp::arg("validState"), bp::arg("validStateAvailable") ) );
        
        }
        bp::register_ptr_to_python< boost::shared_ptr< ompl::base::StateValidityChecker > >();
    }

}
