// This file has been generated by Py++.

#ifndef StateStorage_hpp__pyplusplus_wrapper
#define StateStorage_hpp__pyplusplus_wrapper

void register_StateStorage_class();

#endif//StateStorage_hpp__pyplusplus_wrapper
