// This file has been generated by Py++.

#ifndef StateSamplerSelector_hpp__pyplusplus_wrapper
#define StateSamplerSelector_hpp__pyplusplus_wrapper

void register_StateSamplerSelector_class();

#endif//StateSamplerSelector_hpp__pyplusplus_wrapper
