// This file has been generated by Py++.

#include "boost/python.hpp"
#include "bindings/base.h"
#include "SubspaceStateSampler.pypp.hpp"

namespace bp = boost::python;

struct SubspaceStateSampler_wrapper : ompl::base::SubspaceStateSampler, bp::wrapper< ompl::base::SubspaceStateSampler > {

    SubspaceStateSampler_wrapper(::ompl::base::StateSpace const * space, ::ompl::base::StateSpace const * subspace, double weight )
    : ompl::base::SubspaceStateSampler( boost::python::ptr(space), boost::python::ptr(subspace), weight )
      , bp::wrapper< ompl::base::SubspaceStateSampler >(){
        // constructor
    
    }

    virtual void sampleGaussian( ::ompl::base::State * state, ::ompl::base::State const * mean, double const stdDev ) {
        if( bp::override func_sampleGaussian = this->get_override( "sampleGaussian" ) )
            func_sampleGaussian( boost::python::ptr(state), boost::python::ptr(mean), stdDev );
        else{
            this->ompl::base::SubspaceStateSampler::sampleGaussian( boost::python::ptr(state), boost::python::ptr(mean), stdDev );
        }
    }
    
    void default_sampleGaussian( ::ompl::base::State * state, ::ompl::base::State const * mean, double const stdDev ) {
        ompl::base::SubspaceStateSampler::sampleGaussian( boost::python::ptr(state), boost::python::ptr(mean), stdDev );
    }

    virtual void sampleUniform( ::ompl::base::State * state ) {
        if( bp::override func_sampleUniform = this->get_override( "sampleUniform" ) )
            func_sampleUniform( boost::python::ptr(state) );
        else{
            this->ompl::base::SubspaceStateSampler::sampleUniform( boost::python::ptr(state) );
        }
    }
    
    void default_sampleUniform( ::ompl::base::State * state ) {
        ompl::base::SubspaceStateSampler::sampleUniform( boost::python::ptr(state) );
    }

    virtual void sampleUniformNear( ::ompl::base::State * state, ::ompl::base::State const * near, double const distance ) {
        if( bp::override func_sampleUniformNear = this->get_override( "sampleUniformNear" ) )
            func_sampleUniformNear( boost::python::ptr(state), boost::python::ptr(near), distance );
        else{
            this->ompl::base::SubspaceStateSampler::sampleUniformNear( boost::python::ptr(state), boost::python::ptr(near), distance );
        }
    }
    
    void default_sampleUniformNear( ::ompl::base::State * state, ::ompl::base::State const * near, double const distance ) {
        ompl::base::SubspaceStateSampler::sampleUniformNear( boost::python::ptr(state), boost::python::ptr(near), distance );
    }

};

void register_SubspaceStateSampler_class(){

    { //::ompl::base::SubspaceStateSampler
        typedef bp::class_< SubspaceStateSampler_wrapper, bp::bases< ompl::base::StateSampler >, boost::noncopyable > SubspaceStateSampler_exposer_t;
        SubspaceStateSampler_exposer_t SubspaceStateSampler_exposer = SubspaceStateSampler_exposer_t( "SubspaceStateSampler", bp::init< ompl::base::StateSpace const *, ompl::base::StateSpace const *, double >(( bp::arg("space"), bp::arg("subspace"), bp::arg("weight") )) );
        bp::scope SubspaceStateSampler_scope( SubspaceStateSampler_exposer );
        { //::ompl::base::SubspaceStateSampler::sampleGaussian
        
            typedef void ( ::ompl::base::SubspaceStateSampler::*sampleGaussian_function_type)( ::ompl::base::State *,::ompl::base::State const *,double const ) ;
            typedef void ( SubspaceStateSampler_wrapper::*default_sampleGaussian_function_type)( ::ompl::base::State *,::ompl::base::State const *,double const ) ;
            
            SubspaceStateSampler_exposer.def( 
                "sampleGaussian"
                , sampleGaussian_function_type(&::ompl::base::SubspaceStateSampler::sampleGaussian)
                , default_sampleGaussian_function_type(&SubspaceStateSampler_wrapper::default_sampleGaussian)
                , ( bp::arg("state"), bp::arg("mean"), bp::arg("stdDev") ) );
        
        }
        { //::ompl::base::SubspaceStateSampler::sampleUniform
        
            typedef void ( ::ompl::base::SubspaceStateSampler::*sampleUniform_function_type)( ::ompl::base::State * ) ;
            typedef void ( SubspaceStateSampler_wrapper::*default_sampleUniform_function_type)( ::ompl::base::State * ) ;
            
            SubspaceStateSampler_exposer.def( 
                "sampleUniform"
                , sampleUniform_function_type(&::ompl::base::SubspaceStateSampler::sampleUniform)
                , default_sampleUniform_function_type(&SubspaceStateSampler_wrapper::default_sampleUniform)
                , ( bp::arg("state") ) );
        
        }
        { //::ompl::base::SubspaceStateSampler::sampleUniformNear
        
            typedef void ( ::ompl::base::SubspaceStateSampler::*sampleUniformNear_function_type)( ::ompl::base::State *,::ompl::base::State const *,double const ) ;
            typedef void ( SubspaceStateSampler_wrapper::*default_sampleUniformNear_function_type)( ::ompl::base::State *,::ompl::base::State const *,double const ) ;
            
            SubspaceStateSampler_exposer.def( 
                "sampleUniformNear"
                , sampleUniformNear_function_type(&::ompl::base::SubspaceStateSampler::sampleUniformNear)
                , default_sampleUniformNear_function_type(&SubspaceStateSampler_wrapper::default_sampleUniformNear)
                , ( bp::arg("state"), bp::arg("near"), bp::arg("distance") ) );
        
        }
    }

}
