// This file has been generated by Py++.

#ifndef TimeState_hpp__pyplusplus_wrapper
#define TimeState_hpp__pyplusplus_wrapper

void register_TimeState_class();

#endif//TimeState_hpp__pyplusplus_wrapper
