// This file has been generated by Py++.

#ifndef TimeStateSpace_hpp__pyplusplus_wrapper
#define TimeStateSpace_hpp__pyplusplus_wrapper

void register_TimeStateSpace_class();

#endif//TimeStateSpace_hpp__pyplusplus_wrapper
