// This file has been generated by Py++.

#ifndef UniformValidStateSampler_hpp__pyplusplus_wrapper
#define UniformValidStateSampler_hpp__pyplusplus_wrapper

void register_UniformValidStateSampler_class();

#endif//UniformValidStateSampler_hpp__pyplusplus_wrapper
