// This file has been generated by Py++.

#ifndef ValidStateSampler_hpp__pyplusplus_wrapper
#define ValidStateSampler_hpp__pyplusplus_wrapper

void register_ValidStateSampler_class();

#endif//ValidStateSampler_hpp__pyplusplus_wrapper
