// This file has been generated by Py++.

#ifndef vectorStateSpacePtr_hpp__pyplusplus_wrapper
#define vectorStateSpacePtr_hpp__pyplusplus_wrapper

void register_vectorStateSpacePtr_class();

#endif//vectorStateSpacePtr_hpp__pyplusplus_wrapper
