// This file has been generated by Py++.

#ifndef vectorPlannerSolution_hpp__pyplusplus_wrapper
#define vectorPlannerSolution_hpp__pyplusplus_wrapper

void register_vectorPlannerSolution_class();

#endif//vectorPlannerSolution_hpp__pyplusplus_wrapper
