// This file has been generated by Py++.

#include "boost/python.hpp"
#include "indexing_suite/container_suite.hpp"
#include "indexing_suite/deque.hpp"
#include "bindings/geometric.h"
#include "deque_less__ompl_scope_base_scope_State_ptr___greater_.pypp.hpp"

namespace bp = boost::python;

void register_deque_less__ompl_scope_base_scope_State_ptr___greater__class(){

    bp::class_< std::deque< ompl::base::State* > >("deque_less__ompl_scope_base_scope_State_ptr___greater_")    
        .def( bp::indexing::deque_suite< std::deque< ompl::base::State* > >::with_policies(bp::return_internal_reference< >()) );

}
