// This file has been generated by Py++.

#ifndef KStarStrategy_hpp__pyplusplus_wrapper
#define KStarStrategy_hpp__pyplusplus_wrapper

void register_KStarStrategy_class();

#endif//KStarStrategy_hpp__pyplusplus_wrapper
