// This file has been generated by Py++.

#ifndef KStrategy_hpp__pyplusplus_wrapper
#define KStrategy_hpp__pyplusplus_wrapper

void register_KStrategy_class();

#endif//KStrategy_hpp__pyplusplus_wrapper
