// This file has been generated by Py++.

#ifndef NearestNeighborsLinear_hpp__pyplusplus_wrapper
#define NearestNeighborsLinear_hpp__pyplusplus_wrapper

void register_NearestNeighborsLinear_class();

#endif//NearestNeighborsLinear_hpp__pyplusplus_wrapper
