// This file has been generated by Py++.

#include "boost/python.hpp"
#include "bindings/geometric.h"
#include "PDST.pypp.hpp"

namespace bp = boost::python;

struct PDST_wrapper : ompl::geometric::PDST, bp::wrapper< ompl::geometric::PDST > {

    PDST_wrapper(::ompl::base::SpaceInformationPtr const & si )
    : ompl::geometric::PDST( si )
      , bp::wrapper< ompl::geometric::PDST >(){
        // constructor
    
    }

    virtual void clear(  ) {
        if( bp::override func_clear = this->get_override( "clear" ) )
            func_clear(  );
        else{
            this->ompl::geometric::PDST::clear(  );
        }
    }
    
    void default_clear(  ) {
        ompl::geometric::PDST::clear( );
    }

    void freeMemory(  ){
        ompl::geometric::PDST::freeMemory(  );
    }

    virtual void getPlannerData( ::ompl::base::PlannerData & data ) const  {
        if( bp::override func_getPlannerData = this->get_override( "getPlannerData" ) )
            func_getPlannerData( boost::ref(data) );
        else{
            this->ompl::geometric::PDST::getPlannerData( boost::ref(data) );
        }
    }
    
    void default_getPlannerData( ::ompl::base::PlannerData & data ) const  {
        ompl::geometric::PDST::getPlannerData( boost::ref(data) );
    }

    virtual void setup(  ) {
        if( bp::override func_setup = this->get_override( "setup" ) )
            func_setup(  );
        else{
            this->ompl::geometric::PDST::setup(  );
        }
    }
    
    void default_setup(  ) {
        ompl::geometric::PDST::setup( );
    }

    virtual ::ompl::base::PlannerStatus solve( ::ompl::base::PlannerTerminationCondition const & ptc ) {
        if( bp::override func_solve = this->get_override( "solve" ) )
            return func_solve( boost::ref(ptc) );
        else{
            return this->ompl::geometric::PDST::solve( boost::ref(ptc) );
        }
    }
    
    ::ompl::base::PlannerStatus default_solve( ::ompl::base::PlannerTerminationCondition const & ptc ) {
        return ompl::geometric::PDST::solve( boost::ref(ptc) );
    }

    virtual void checkValidity(  ) {
        if( bp::override func_checkValidity = this->get_override( "checkValidity" ) )
            func_checkValidity(  );
        else{
            this->ompl::base::Planner::checkValidity(  );
        }
    }
    
    void default_checkValidity(  ) {
        ompl::base::Planner::checkValidity( );
    }

    virtual void setProblemDefinition( ::ompl::base::ProblemDefinitionPtr const & pdef ) {
        if( bp::override func_setProblemDefinition = this->get_override( "setProblemDefinition" ) )
            func_setProblemDefinition( pdef );
        else{
            this->ompl::base::Planner::setProblemDefinition( pdef );
        }
    }
    
    void default_setProblemDefinition( ::ompl::base::ProblemDefinitionPtr const & pdef ) {
        ompl::base::Planner::setProblemDefinition( pdef );
    }

};

void register_PDST_class(){

    { //::ompl::geometric::PDST
        typedef bp::class_< PDST_wrapper, bp::bases< ::ompl::base::Planner >, boost::noncopyable > PDST_exposer_t;
        PDST_exposer_t PDST_exposer = PDST_exposer_t( "PDST", bp::init< ompl::base::SpaceInformationPtr const & >(( bp::arg("si") )) );
        bp::scope PDST_scope( PDST_exposer );
        bp::implicitly_convertible< ompl::base::SpaceInformationPtr const &, ompl::geometric::PDST >();
        { //::ompl::geometric::PDST::clear
        
            typedef void ( ::ompl::geometric::PDST::*clear_function_type)(  ) ;
            typedef void ( PDST_wrapper::*default_clear_function_type)(  ) ;
            
            PDST_exposer.def( 
                "clear"
                , clear_function_type(&::ompl::geometric::PDST::clear)
                , default_clear_function_type(&PDST_wrapper::default_clear) );
        
        }
        { //::ompl::geometric::PDST::freeMemory
        
            typedef void ( PDST_wrapper::*freeMemory_function_type)(  ) ;
            
            PDST_exposer.def( 
                "freeMemory"
                , freeMemory_function_type( &PDST_wrapper::freeMemory ) );
        
        }
        { //::ompl::geometric::PDST::getGoalBias
        
            typedef double ( ::ompl::geometric::PDST::*getGoalBias_function_type)(  ) const;
            
            PDST_exposer.def( 
                "getGoalBias"
                , getGoalBias_function_type( &::ompl::geometric::PDST::getGoalBias ) );
        
        }
        { //::ompl::geometric::PDST::getPlannerData
        
            typedef void ( ::ompl::geometric::PDST::*getPlannerData_function_type)( ::ompl::base::PlannerData & ) const;
            typedef void ( PDST_wrapper::*default_getPlannerData_function_type)( ::ompl::base::PlannerData & ) const;
            
            PDST_exposer.def( 
                "getPlannerData"
                , getPlannerData_function_type(&::ompl::geometric::PDST::getPlannerData)
                , default_getPlannerData_function_type(&PDST_wrapper::default_getPlannerData)
                , ( bp::arg("data") ) );
        
        }
        { //::ompl::geometric::PDST::getProjectionEvaluator
        
            typedef ::ompl::base::ProjectionEvaluatorPtr const & ( ::ompl::geometric::PDST::*getProjectionEvaluator_function_type)(  ) const;
            
            PDST_exposer.def( 
                "getProjectionEvaluator"
                , getProjectionEvaluator_function_type( &::ompl::geometric::PDST::getProjectionEvaluator )
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::ompl::geometric::PDST::setGoalBias
        
            typedef void ( ::ompl::geometric::PDST::*setGoalBias_function_type)( double ) ;
            
            PDST_exposer.def( 
                "setGoalBias"
                , setGoalBias_function_type( &::ompl::geometric::PDST::setGoalBias )
                , ( bp::arg("goalBias") ) );
        
        }
        { //::ompl::geometric::PDST::setProjectionEvaluator
        
            typedef void ( ::ompl::geometric::PDST::*setProjectionEvaluator_function_type)( ::ompl::base::ProjectionEvaluatorPtr const & ) ;
            
            PDST_exposer.def( 
                "setProjectionEvaluator"
                , setProjectionEvaluator_function_type( &::ompl::geometric::PDST::setProjectionEvaluator )
                , ( bp::arg("projectionEvaluator") ) );
        
        }
        { //::ompl::geometric::PDST::setProjectionEvaluator
        
            typedef void ( ::ompl::geometric::PDST::*setProjectionEvaluator_function_type)( ::std::string const & ) ;
            
            PDST_exposer.def( 
                "setProjectionEvaluator"
                , setProjectionEvaluator_function_type( &::ompl::geometric::PDST::setProjectionEvaluator )
                , ( bp::arg("name") ) );
        
        }
        { //::ompl::geometric::PDST::setup
        
            typedef void ( ::ompl::geometric::PDST::*setup_function_type)(  ) ;
            typedef void ( PDST_wrapper::*default_setup_function_type)(  ) ;
            
            PDST_exposer.def( 
                "setup"
                , setup_function_type(&::ompl::geometric::PDST::setup)
                , default_setup_function_type(&PDST_wrapper::default_setup) );
        
        }
        { //::ompl::geometric::PDST::solve
        
            typedef ::ompl::base::PlannerStatus ( ::ompl::geometric::PDST::*solve_function_type)( ::ompl::base::PlannerTerminationCondition const & ) ;
            typedef ::ompl::base::PlannerStatus ( PDST_wrapper::*default_solve_function_type)( ::ompl::base::PlannerTerminationCondition const & ) ;
            
            PDST_exposer.def( 
                "solve"
                , solve_function_type(&::ompl::geometric::PDST::solve)
                , default_solve_function_type(&PDST_wrapper::default_solve)
                , ( bp::arg("ptc") ) );
        
        }
        PDST_exposer.def("solve", (::ompl::base::PlannerStatus(::ompl::base::Planner::*)( double ))(&::ompl::base::Planner::solve), (bp::arg("solveTime")) );
        PDST_exposer.def("setProblemDefinition",&::ompl::base::Planner::setProblemDefinition,
                            &PDST_wrapper::default_setProblemDefinition, (bp::arg("pdef")) );
        PDST_exposer.def("checkValidity",&::ompl::base::Planner::checkValidity,
                        &PDST_wrapper::default_checkValidity );
    }

}
