// This file has been generated by Py++.

#ifndef SimpleSetup_hpp__pyplusplus_wrapper
#define SimpleSetup_hpp__pyplusplus_wrapper

void register_SimpleSetup_class();

#endif//SimpleSetup_hpp__pyplusplus_wrapper
